# Generated by Django 3.1.13 on 2021-10-16 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_edicao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
