# Generated by Django 3.1.13 on 2021-11-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211025_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('1', 'Chefe do Departamento'), ('2', 'Inspector'), ('3', 'Super User')], default='1', max_length=3),
        ),
    ]
