# Generated by Django 3.1.13 on 2021-10-06 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proprietario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculo.marca')),
            ],
        ),
        migrations.CreateModel(
            name='RegistoInicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_motor', models.CharField(max_length=20, unique=True)),
                ('numero_quadro', models.CharField(max_length=20, unique=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('lotacao', models.PositiveIntegerField()),
                ('tipo_veiculo', models.CharField(choices=[('1', 'Ligerio'), ('2', 'Pesado')], default='1', max_length=1)),
                ('data_registo', models.DateTimeField(auto_now=True)),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculo.cor')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculo.modelo')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprietario.proprietario')),
            ],
        ),
    ]
