# Generated by Django 3.1.13 on 2021-10-06 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registo', models.DateTimeField()),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_operador_id', to=settings.AUTH_USER_MODEL)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_proprietario_id', to='accounts.pessoa')),
            ],
        ),
    ]
