# Generated by Django 3.1.13 on 2021-10-06 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculo', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proprietario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbeteViatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now=True)),
                ('data_validade', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('proprietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proprietario.proprietario')),
                ('registo_inicial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='veiculo.registoinicial')),
            ],
        ),
        migrations.CreateModel(
            name='VerbeteCarta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carta', models.CharField(max_length=20, unique=True)),
                ('data_emissao', models.DateTimeField(auto_now=True)),
                ('data_validade', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('1', 'Ligerio Amador'), ('2', 'Ligerio Profissional'), ('3', 'Pesado')], default='1', max_length=1)),
                ('proprietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proprietario.proprietario')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoVerbeteViatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now=True)),
                ('data_validade', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verbete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbete.verbeteviatura')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoVerbeteCarta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now=True)),
                ('data_validade', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verbete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbete.verbetecarta')),
            ],
        ),
    ]
