# Generated by Django 3.1.13 on 2021-10-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbete', '0002_auto_20211019_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbetecarta',
            name='categoria',
            field=models.CharField(choices=[('1', 'Lig Amador'), ('2', 'Ligerio Profissional'), ('3', 'Pesado')], default='1', max_length=1),
        ),
    ]
