# Generated by Django 3.1.13 on 2021-10-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbete', '0003_auto_20211021_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verbeteviatura',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='verbetecarta',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/viatura'),
        ),
    ]
