# Generated by Django 3.1.13 on 2021-10-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbete', '0004_auto_20211030_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbeteviatura',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/viatura'),
        ),
    ]
