# Generated by Django 3.1.13 on 2021-10-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbete', '0005_verbeteviatura_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbetecarta',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='viatura'),
        ),
        migrations.AlterField(
            model_name='verbeteviatura',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='viatura'),
        ),
    ]
